name: pre-commit
description: run pre-commit
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
runs:
  using: composite
  steps:
  - run: python -m pip install pre-commit
    shell: bash
  - run: python -m pip freeze --local
    shell: bash
  - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
    with:
      path: ~/.cache/pre-commit
      key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
  - env:
      EXTRA_ARGS: ${{ inputs.extra_args }}
    run: pre-commit run --show-diff-on-failure --color=always $EXTRA_ARGS
    shell: bash
